# render.yaml
services:
  - type: web
    name: strive-code-ai
    env: docker
    region: oregon
    plan: standard
    branch: main
    buildCommand: ./scripts/bootstrap.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PORT
        sync: false
